### ISSUE TITLE
imgur broken in 1.3.0

### ISSUE THREAD

**Issue by bbluemel** [olav-st/screencloud-plugins#29]
In Screencloud v 1.3.0 whenever trying to install the imgur plugin I get the following, which makes imgurl disabled for use.

---------------------------
Script error in plugin 'imgur'
---------------------------
Error in file: C:/Users/Ben/AppData/Roaming/screencloud/ScreenCloud/plugins/imgur/main.py
Traceback (most recent call last):
  File "<string>", line 5, in <module>
  File "C:/Users/Ben/AppData/Roaming/screencloud/ScreenCloud/plugins\imgur\modules\pyimgur\__init__.py", line 45, in <module>
    import requests  # NOQA
  File "C:/Users/Ben/AppData/Roaming/screencloud/ScreenCloud/plugins\imgur\modules\requests\__init__.py", line 58, in <module>
    from . import utils
  File "C:/Users/Ben/AppData/Roaming/screencloud/ScreenCloud/plugins\imgur\modules\requests\utils.py", line 12, in <module>
    import cgi
  File "C:\Program Files (x86)\ScreenCloud\python35.zip\cgi.py", line 39, in <module>
  File "C:\Program Files (x86)\ScreenCloud\python35.zip\email\parser.py", line 12, in <module>
  File "C:\Program Files (x86)\ScreenCloud\python35.zip\email\feedparser.py", line 27, in <module>
  File "C:\Program Files (x86)\ScreenCloud\python35.zip\email\message.py", line 16, in <module>
  File "C:\Program Files (x86)\ScreenCloud\python35.zip\email\utils.py", line 30, in <module>
ImportError: DLL load failed: The specified module could not be found.

---------------------------
OK   
---------------------------

Thanks

Ben

**Comment by bbluemel** [comment]
Seems a clean install as per https://github.com/olav-st/screencloud/issues/225 solves this :)
